export const clientRoutes = {
    home: "/",
    events: "/events",
    rankings: "/rankings",
    clubs: "/clubs",
    membershipPlans: "/membership-plans",
    players: "/players",
    playerProfile: (id: string) => `/players/${id}`,
    profile: "/profile",
    profileEdit: "/profile/edit",
    signIn: "/auth/sign-in",
    signUp: "/auth/sign-up",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    admin: "/admin",
    eventsCreate: "/events/create",
    dashboard: "/dashboard",

    steps: (step: number) => `/new-visitor/step-${step}`,
    claimHistory: "/claim-history",
    eventDetail: (id: number) => `/events/${id}`,
    clubDetail: (id: number) => `/clubs/${id}`,
};
